[workspace]
resolver = "2"
members = [
    "crates/mirage-matrix-macros",
    "crates/mirage-matrix",
    "crates/mirage-assets",
    "crates/mirage-core",
    "crates/mirage-geometry",
    "crates/mirage-synapse",
    "crates/mirage-compiler",
    "crates/mirage-executor",
    "crates/mirage-math",
    "crates/mirage-platform",
    "crates/mirage-renderer",
    "crates/mirage-audio",
    "crates/mirage-physics",
    "crates/mirage-animation",
    "crates/mirage-ai",
    "crates/mirage-net",
    "crates/mirage-ui",
    "crates/mirage-compute", "crates/mirage-memory-oasis", "crates/mirage-mkr-core",
    "crates/mirage-query",
    "crates/mirage-mts",
    "crates/mirage-cek",
    "crates/mirage-morphogenic",
]
default-members = ["crates/mirage-renderer"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
