[package]
name = "mirage-matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
mirage-core = { path = "../mirage-core" }
mirage-math = { path = "../mirage-math" }
petgraph = "0.6"
uuid = { version = "1.0", features = ["v4"] }
fxhash = "0.2"
mirage-matrix-macros = { path = "../mirage-matrix-macros" }
bytemuck = "1.25.0"
