[package]
name = "mirage-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
mirage-geometry = { path = "../mirage-geometry" }
mirage-synapse = { path = "../mirage-synapse" }
mirage-compiler = { path = "../mirage-compiler" }
mirage-math = { path = "../mirage-math" }
mirage-core = { path = "../mirage-core" }
rayon = "1.8"
crossbeam-deque = "0.8"
