[package]
name = "mirage-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
mirage-matrix = { path = "../mirage-matrix" }
mirage-core = { path = "../mirage-core" }
mirage-geometry = { path = "../mirage-geometry" }
winit = "0.29"
wgpu = "0.19"
pollster = "0.3"
bytemuck = { version = "1.15", features = ["derive"] }
glam = "0.32.1"
